- lib/rails_semantic_logger/extensions/action_controller/log_subscriber.rb
@reidmorrison's solution for the issue #35
> Since Semantic Logger wants a hash, and we would probably want all parameters, since that is what it appears Rails is logging in #inspect, how about the following change?
> Fix for #35

- lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb
We just updated to Rails 5.0.3 and noticed we were getting exceptions when running `rails db:reset`. It turns out that the [API changed in 5.0.3](https://github.com/rails/rails/compare/v5.0.2...v5.0.3#diff-eba6b59bacb9a1d88646145ed1ff4c86R54) to match 5.1.
This patch changes the version sniffing to assume >= 5.0.3 will use the new API. It's possible that it may change back to 5.0.2 behaviour in a 5.0.4 release, but we should be able to handle this with additional predicates.
Before
After
Couple of questions:
1. Are you okay with changing the version sniffing to do string comparisons? It lets you easily test against the patch number.
2. I wasn't sure how far to go with testing. Do you want to test against 5.0.3 as well as 5.x? It looks like we assume the latest stable version is good …
> Fix log_subscriber monkey patch for Rails 5.0.3.

- README.md
Are these the correct versions now? I can update accordingly, I just went off the travis config.
Thanks!
> Update rails and ruby versions supported in readme

- lib/rails_semantic_logger/extensions/action_controller/log_subscriber.rb
- test/controllers/dashboard_controller_test.rb
- test/dummy/app/controllers/application_metal_controller.rb
- test/dummy/app/controllers/dashboard_controller.rb
- test/dummy/config/routes.rb
Ultimately, `rails_semantic_logger` should be configurable to use a different class as the base.
Most (rails) applications apply modifications at the `ApplicationController` level, such as including `SemanticLogger::Loggable`. Gems/Libraries such as `Doorkeeper` (ironically an example where this is breaking and the catalyst for this fix) allow the developer to configure the class name of which all controllers inherit from.
```
Doorkeeper.configure do
base_controller 'ApplicationController'
end
```
`Doorkeeper` coincidentally has a few controllers that do not inherit from `ActionController::Base`, so, even if `rails_semantic_logger` provided a configuration option for `base_controller` (similar to `Doorkeeper`), this illustrates a situation where `rails_semantic_logger` could be a bit more …
> If logger doesn't exist, fallback to ActionController::Base.logger

- lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb
As mentioned in https://github.com/rocketjob/rails_semantic_logger/issues/55 Rails 5.1.5 changed the method `type_casted_binds` to accept only one parameter:
https://github.com/rails/rails/blob/v5.1.5/activerecord/lib/active_record/log_subscriber.rb#L45
Using the same approach as for Rails 5.2 solves the issue.
> Fix type_casted_binds call with one parameter for Rails 5.1.5

- lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb
Checked on Rails 5.1.3
Before changes not put query params in binds hash
Maybe the same fix need to condition 'Rails::VERSION::MAJOR >= 5 # >= 5.1.5'
> Add ActiveRecord request params to binds hash

- lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb
In binds placed the arrays of values instead values
This fix missed values. For example when we use BETWEEN as attribute i want see both edges of range.
Probably the same fix you'll used in other versions of Rails
>  Fix problem for the attributes with several values for some Rails version

- lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb
Looks like 5.0.7 also has the single-parameter version of
type_casted_binds:
https://github.com/rails/rails/blob/v5.0.7/activerecord/lib/active_record/log_subscriber.rb#L50
Related to #60
> Use 5.1.5 method of binding values when using Rails 5.0.7

- lib/rails_semantic_logger.rb
- lib/rails_semantic_logger/delayed_job/plugin.rb
- lib/rails_semantic_logger/engine.rb
Currently, the DelayedJob logging integration does not work when the workers are started using the `bin/delayed_job start` command included in the gem to create multiple workers as daemons. This is because the file handle is not being re-opened after the daemon processes are forked.
This PR adds a custom Delayed::Plugin to reopen the log file before the worker begins picking up jobs.
> DelayedJob Logging Fix

- lib/rails_semantic_logger/engine.rb
If ActiveRecord is available, but not previously required this breaks auto-detection for [some other gems](https://github.com/CanCanCommunity/cancancan/blob/1.17.0/lib/cancan/controller_resource.rb#L224)
For example
```ruby
if defined?(ActiveRecord) && ActiveRecord::VERSION::MAJOR == 3
```
This will fail with `uninitialized constant ActiveRecord::VERSION` if full active record is not required, as the gem only requires the log subscriber.
Conditionally require `active_record/log_subscriber` only if `ActiveRecord` is already defined
> don't require ActiveRecord if it's not already available

- lib/rails_semantic_logger/extensions/active_job/logging.rb
- test/active_job_test.rb
Right now when I add `rails_semantic_logger` to an application with `active_job` I have rather useless lines in the log. However this could/should be improved. Events have structured payload which comes handy in the logs.
https://github.com/rails/rails/blob/master/activejob/lib/active_job/logging.rb
One probably would want to refuse native job adapter logging when this one is setup.
Overriding `ActiveJob::Logging::LogSubscriber` and re-subscribing to the `*.active_job` events does the trick.
> Add proper ActiveJob events subscription

- Gemfile
- lib/rails_semantic_logger/engine.rb
- rails_semantic_logger.gemspec
The number of dependencies Rails gem is requiring is growing by at least 2 gems with every major release. Rails Semantic Logger doesn't need 14 dependencies to run.
I replaced the `rails` gem with the `railties` which results in a lighter dependencies footprint, which means it installs faster and actually let's the end-user to decide if they want to bring Sprockets as a dependency.
I'm not sure if this is the right way to achieve what I want, please advise if changes are needed. Thanks a lot for all this amazing work!
> Add the dependencies we actually use.

- .travis.yml
This PR drops a now-unused configuration directive in the CI file. This simplifies the file.
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for more details
> Travis: Drop unused configuration sudo: false

- lib/rails_semantic_logger/active_record/log_subscriber.rb
- test/active_record_test.rb
The following error was happening when using semantic logging with sidekiq + activerecord on Rails 6
```
Could not log "sql.active_record" event. TypeError: wrong argument type Proc (must respond to :each) ["/Users/arnaud.lachaume/Sites/rails_semantic_logger/lib/rails_semantic_logger/active_record/log_subscriber.rb:102:in `zip'", "/Users/arnaud.lachaume/Sites/rails_semantic_logger/lib/rails_semantic_logger/active_record/log_subscriber.rb:102:in `bind_values_v5_0_3'", "/Users/arnaud.lachaume/Sites/rails_semantic_logger/lib/rails_semantic_logger/active_record/log_subscriber.rb:33:in `sql'", "/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0.beta1/lib/active_support/subscriber.rb:96:in `finish'", "/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0.beta1/li …
```
> Fix logging of SQL queries when query cache is in use

- lib/rails_semantic_logger.rb
Rails 6 store `AS::LogSubscriber#patterns` in a hash where key is
event pattern name rather than an array of event patterns names.
Since Rails version 6, default Rails log subscribers aren't unsubscribed to be replaced by semantic logger so their messages keep showing in log output.
Detect how subscribed events object is storing patterns and get their list accordingly.
The change in Rails subscriber can be viewed in here
https://github.com/rails/rails/commit/ca19b7f5d86aa590077766cbe8006f952b6d4296#diff-e96e89d85fdb9861738081367cc402e0R124
> Fix unsubscribing notifications in rails v6

- lib/rails_semantic_logger/engine.rb
There are several gems that open `Spring` module to register a new command:
https://github.com/jonleighton/spring-commands-rspec/blob/master/lib/spring/commands/rspec.rb
https://github.com/pluff/spring-commands-crystalball/blob/master/lib/spring/commands/crystalball.rb
So when we run an application without spring and reach this line:
```
Spring.after_fork { |_job| ::SemanticLogger.reopen } if defined?(Spring)
```
`Spring` is defined and it tries to invoke after_fork which doesn't exist in those gems.
This PR fixes this problem for apps running without Spring. With Spring this method exists. 
> Check the specific method existance for Spring after_fork

- lib/rails_semantic_logger/engine.rb
Resolves #94
Sidekiq 6.0 has deprecated usage of `Sidekiq::Logger`. `Sidekiq::Logger` is an internal module which applications should not be using. Instead applications should be using `Sidekiq.logger`, as is documented here: https://github.com/mperham/sidekiq/wiki/Logging#api-changes
This PR attempts to stay backwards compatible by keeping the existing behaviour when `Sidekiq::Logging` still exists and use `Sidekiq.logger` when `Sidekiq::Logging` doesn't exist (which should be the case for Sidekiq 6.0+). 
> Use Sidekiq.logger when Sidekiq::Logging is unavailable

- README.md
https://github.com/rocketjob/rails_semantic_logger/issues/99#issuecomment-616265772
Correct the README in Rails supported version.
Ref: https://github.com/rocketjob/semantic_logger/commit/e82ef88c1955b007c51e25da5e4935ff49688360
> Edit supported Ruby and Rails versions

- lib/rails_semantic_logger.rb
- lib/rails_semantic_logger/engine.rb
- lib/rails_semantic_logger/options.rb
Needed to disable semantic logger in development mode.
* Added in a new config option that allows you to disable semantic logging within Rails
* Moved rails server patch near the other rails patches
* Defaulted the `disabled` config to `false` so semantic logging is enabled by default
The PR looks large because a lot of block formatting that was needed.
Is this something that you guys are interested in supporting?
Should the config be called `enabled` instead?
> Disabling semantic logger via config

- lib/rails_semantic_logger/action_controller/log_subscriber.rb
Follow on from https://github.com/rocketjob/rails_semantic_logger/pull/110
This avoids infinite recursion while trying to serialise Request and Response objects.
I'm not 100% comfortable with this, but neither `ActionDispatch::Request` nor `ActionDispatch::Response` objects can be serialised with `to_json` under Rails 6.1.rc1.
This work-around is possibly a bit too much of a hammer?
> Omit request and response from output

- lib/rails_semantic_logger/action_controller/log_subscriber.rb
- lib/rails_semantic_logger/action_view/log_subscriber.rb
- lib/rails_semantic_logger/active_record/log_subscriber.rb
- test/active_record_test.rb
- test/controllers/articles_controller_test.rb
Since Rails 6, allocations have been logged during ActionController request logging, ActionView rendering, and ActiveRecord querying. This change adds those metrics to the payload (similar to `db_runtime` and `view_runtime`).
A concern: `allocations` is on `event` rather than `event.payload`, so this doesn't quite match up like `duration` does, so we would need to make changes to `SemanticLogger` to move `allocations` up to the log struct.
> Adds allocations to the payload for controller, view, and sql logs

- Gemfile
- lib/rails_semantic_logger/action_controller/log_subscriber.rb
- test/controllers/dashboard_controller_test.rb
- test/dummy/config/initializers/payload_collector.rb
- test/payload_collector.rb
- test/test_helper.rb
The absence of `payload[:params]` in other active support notification subscribers:
I use [yabeda-rails gem](https://github.com/yabeda-rb/yabeda-rails) to monitor rails application metrics. It is based on the Rails notification instrumentation [here](https://github.com/yabeda-rb/yabeda-rails/blob/master/lib/yabeda/rails.rb#L46-L65).
After rails_semantic_logger plug-in, I've noticed, that [request params in payload](https://github.com/yabeda-rb/yabeda-rails/blob/master/lib/yabeda/rails.rb#L49-L50) become empty. It's because of rails_semantic_logger's callback mofidies original hash, instead of duplication.
Duplicates local payload params instead of modifying original one.
> Fix notification payload params absence

- lib/rails_semantic_logger/action_view/log_subscriber.rb
- lib/rails_semantic_logger/active_record/log_subscriber.rb
- Fixes a bug where `cache_hit` and `cache_hits` were not correctly added to the payload.
- Adds whether a sql statement came from the query cache or not. This information is shown in regular Rails logs by prepending `CACHE` to the log message:
> Add missing caching information to logs

- lib/rails_semantic_logger/engine.rb
We have a rails app where we don't `require "rails"`, but only require a subset of the action*/active* gems to make it work. (It's a very simple app!)
For some of these if you haven't loaded in the Rails gem, then the classes within RailsSemanticLogger cause the `defined?` check to pass and then the code to blow up. Instead change the code here to be explicit in checking these are top level constants, not nested ones inside this gem.
> Be explicit with rails constants in the Engine

- lib/rails_semantic_logger/engine.rb
This commit PR the regex used for the quiet_assets setting with the content of `Rails.application.config.relative_url_root`[1]. Quiet assets should now also work with applications deployed in a subdirectory.
[1] https://guides.rubyonrails.org/v6.1.3/configuring.html#deploy-to-a-subdirectory-relative-url-root
> Take Rails' relative_url_root into account when filtering out Rack asset requests

- lib/rails_semantic_logger/rack/logger.rb
https://github.com/rocketjob/rails_semantic_logger/issues/128
use request.remote_ip instead of request.ip to log the correct IP of the requester
> Fix #128 using request.remote_ip

- lib/rails_semantic_logger/active_record/log_subscriber.rb
- test/active_record_test.rb
Because it is then turned into an empty string key in json and
Elasticsearch refuses to parse it.
Fixes #131
> Don't use `nil` as payload key.

- lib/rails_semantic_logger/extensions/action_controller/live.rb
- lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb
- lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb
- lib/rails_semantic_logger/extensions/active_support/logger.rb
```
$ RUBYOPT='-w' bundle exec rspec   
…/rails_semantic_logger-4.6.0/lib/rails_semantic_logger/extensions/action_controller/live.rb:2: warning: possibly useless use of :: in void context
…/rails_semantic_logger-4.6.0/lib/rails_semantic_logger/extensions/action_controller/live.rb:5: warning: method redefined; discarding old log_error
…/actionpack-6.1.4/lib/action_controller/metal/live.rb:307: warning: previous definition of log_error was here
…/rails_semantic_logger-4.6.0/lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb:2: warning: possibly useless use of :: in void context
…/rails_semantic_logger-4.6.0/lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb:7: warning: method redefined; discarding old log_error …
```
> Silence method redifinition warnings

- lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb
- lib/rails_semantic_logger/extensions/action_controller/live.rb
- lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb
- lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb
- lib/rails_semantic_logger/extensions/active_job/logging.rb
- lib/rails_semantic_logger/extensions/rails/server.rb
Fails in projects with no warning policy, e.g. using `warning` gem with raise on warn. 
Overall warnings are bad.
1. Eliminate warnings ` warning: possibly useless use of :: in void context` in several files
2. Eliminate method redefinition warning in couple of files
> Fix ruby warnings

- lib/rails_semantic_logger/extensions/rails/server.rb
N/A.
Starting a rails server that already features a console appender results in the following warning:
> 2022-02-02 18:52:19.697203 W [386462:52820] SemanticLogger::Appenders -- Ignoring attempt to add a second console appender: SemanticLogger::Appender::IO since it would result in duplicate console output.
This change fixes it.
---
> Avoid warning when attempting to add a second console appender

- lib/rails_semantic_logger/extensions/rails/server.rb
I'm experiencing the following error when I run some Rake tasks that use
`rails_semantic_logger`:
```
NameError: undefined method `log_to_stdout' for class `Rails::Server'
```
I don't quite understand how `log_to_stdout` could be undefined, but
this fixes things for me, and seems to be a valid approach to the issue,
so I thought I'd try to land it upstream, so I can upgrade from v4.6.1.
> Only undefine Rails::Server#log_to_stdout if it's defined

- lib/rails_semantic_logger/active_record/log_subscriber.rb
Fixes #156 
This causes rendering of bind values to use the more modern style adopted in Rails 6.1. I've tested this on my own app and it works fine, but if there is a place to add a test case for this please let me know.
> Fix rendering of bind values for Rails 7

- lib/rails_semantic_logger/action_mailer/log_subscriber.rb
Fixes the warning regarding a mismatched indentation at `lib/rails_semantic_logger/action_mailer/log_subscriber.rb`:
> warning: mismatched indentations at 'else' with 'if' at 20
You can run `RUBYOPT='-w' bundle exec rake test` to check the warning mentioned above.
Only indentation :) We have a project that raises errors on warning so this is breaking our CI.
> Fix if-else mismatched indentations warning

- .github/workflows/ci.yml
- Appraisals
- gemfiles/rails_7.0.gemfile
Adds Ruby 3.2 to the CI matrix, and resolves a few other CI matrix issues.  These are:
1. Set the Rails 5.2 / jruby to use jruby-9.3 because jruby (9.4) is now a 3.1 compatible Ruby, and thus doesn't work with Rails 5.2
2. Removed two duplicate entries in the CI matrix
3. Added a Rails 7.0 / jruby entry.  This required minor modifications to the Appraisals / rails_7.0.gemfile to update the `activerecord-jdbcsqlite3-adapter` to `~> 7.0`
Also updated the version of the checkout action to `v3`
> Add Ruby 3.2 to the CI matrix, fixes other CI issues

- lib/rails_semantic_logger/engine.rb
Sidekiq 7 API has changed and `Sidekiq.logger=` is not available anymore.
Changing Sidekiq config can be achieved through `configure_client` and `configure_server` methods.
This PR checks whether Sidekiq 7 is available and injects the semantic logger accordingly.
> Add support for Sidekiq 7.x

- lib/rails_semantic_logger/engine.rb
Since https://github.com/reidmorrison/rails_semantic_logger/pull/168 I'm getting a `cannot load such file -- action_mailer/log_subscriber (LoadError)`. 
ActionMailer isn't loaded because as an optimization we are only loading some rails frameworks all listed here: https://guides.rubyonrails.org/initialization.html#railties-lib-rails-all-rb. We also exclude it from our Gemfile so it isn't available.
Like `ActiveRecord` check if the railtie is defined before loading and swapping the subscriber
> fix: require rails subscribers if defined

- lib/rails_semantic_logger/engine.rb
Fixes the broken build/functionality for Ruby 2.5 and 2.6.  The use of 2.7+ syntax in `lib/rails_semantic_logger/engine.rb` breaks this library when used with those Rubies.
> Don't use 2.7+ syntax, which breaks compatibility with earlier Ruby versions

- lib/rails_semantic_logger/action_mailer/log_subscriber.rb
The `log_arguments` setting in Mailer does not suppress argument logging when set to `false`. Arguments are still included in the payload.
Corrected typos in the `formatted_args` method, which previously resulted in arguments being logged regardless of the `log_arguments` setting.
---
> Fix: `log_arguments` of Mailer does not work properly

- .github/workflows/ci.yml
- lib/rails_semantic_logger/extensions/active_support/logger.rb
Rails 7.1 dropped this method from ActiveSupport::Logger so trying to undefine it throws on boot
Removed that one undef line
> fix: remove undef :broadcast since ActiveSupport::Logger dropped it

- lib/rails_semantic_logger/active_job/log_subscriber.rb
- test/active_job_test.rb
We found an issue with the logs of ActiveJobs.
When a job has an error or throws an abort or  Rails Semantic Logger with still log "Enqueued Job..." despite the job not being enqueued.
```ruby
class NoOpJob < ApplicationJob
before_enqueue -> { throw :abort }
end
NoOpJob.perform_later
```
```
```
Please find the corresponding log messages in the [Rails Repo](https://github.com/rails/rails/blob/4c9a990ffda8817e531b70c19c57ccc3078c0a22/activejob/lib/active_job/log_subscriber.rb#L6-L28) that differentiate between three events: errors, :abort and successful enqueing.
We extended both methods `#enqueue` and `#enqueue_at` and also added test cases for those.
```ruby
class NoOpJob < ApplicationJob
before_enqueue -> { throw :abort }
end
NoOpJob.perform_later
```
```
2023-07-26 15:04:37.069003 I …
```
> Fix enqueue messages for ActiveJob

- rails_semantic_logger.gemspec
looks like the resulting url is missing the semantic v of the version tag
> fix source_code_uri

- lib/rails_semantic_logger/extensions/active_job/logging.rb
I was getting "undefined method 'tagged' for nil:NilClass (NoMethodError)" exceptions in `ActiveJob::Logging` as `logger` was `nil`. I wasn't sure whether I was not setting up logging correctly so I started out with a vanilla Rails project, created an active job class and raised an exception in it. `logger` wasn't set there either but `ActiveJob` [handles this case gracefully](https://github.com/rails/rails/blob/2f26d01a93c619c3327e6d310994f40b2538b6f6/activejob/lib/active_job/logging.rb#L22).
This pull request adds them same handling to the Rails semantic logger.
> fix: handle nil logger in `ActiveJob::Logging`

- lib/rails_semantic_logger/engine.rb
This will remove the warning "No valid API key has been set, notifications will not be sent" that will be logged in all environments as the Bugnsag api key hasn't been set yet as that happens later in the initialization process.
See https://github.com/bugsnag/bugsnag-ruby/blob/bdfbf3972f2137b3b9b95194a6bedf9c8edf6555/lib/bugsnag.rb#L61
> Disable Bugsnag api key validation

- lib/rails_semantic_logger.rb
- lib/rails_semantic_logger/extensions/rackup/server.rb
Closes  #198
Clones `Rack::Server` monkeypatch to `Rackup::Server`
> fix: rack server deprecated in rack 3

- lib/rails_semantic_logger.rb
rails_semantic logger has an optional dependency on Rackup.
Unfortunately, Bundler doesn't have a concept of an optional dependency, meaning that it doesn't enforce the loading of gems that aren't declared as a requirement in the gemspec. This means that rails_semantic_logger behavior actually depends on the ordering inside the Gemfile, and I don't think that was anyone's intention. 
This change force-preloads Rackup if it's available or works a usual if not. 
----
> fix: Ensure the load order of the optional dependency of Rackup

- lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb
- test/controllers/articles_controller_test.rb
- test/dummy/app/controllers/articles_controller.rb
- test/dummy/config/application.rb
- test/dummy/config/environments/test.rb
This should fix https://github.com/reidmorrison/rails_semantic_logger/issues/203
Added test for ActionDispatch::DebugExceptions and fixed couple of rails 7.1 deprecations in tests
> Fix ActionDispatch::DebugExceptions extension deprecation on rails 7.1

- lib/rails_semantic_logger/engine.rb
When combining Semantic Logger with other gems that use the `Resque` namespace and the host app does not use the [`resque` gem](https://rubygems.org/gems/resque), Semantic logger causes a failure during the boot up sequence.
The change makes Resque detection more robust in order to avoid a false positive detection and the subsequent failure in the host's app boot up sequence.
This also aligns the detection with other instances of detecting Resque:
https://github.com/reidmorrison/rails_semantic_logger/blob/eadda203513334f850bc0bc809c295d26642649c/lib/rails_semantic_logger/engine.rb#L108
and detecting other forking:
https://github.com/reidmorrison/rails_semantic_logger/blob/eadda203513334f850bc0bc809c295d26642649c/lib/rails_semantic_logger/engine.rb#L245
---
By submitting this pull request, …
> fix: avoid false positives during Resque detection

- lib/rails_semantic_logger/options.rb
None
Semantic Logger suggests to use Amazing Print since https://github.com/reidmorrison/semantic_logger/commit/22ca2027910ba80218893fd2596df43f67566497
This updates the doc to suggest `Awesome Print` following the Semantic Logger changes.
> Replace Awesome Print to Amazing Print

- lib/rails_semantic_logger/action_controller/log_subscriber.rb
- lib/rails_semantic_logger/engine.rb
- lib/rails_semantic_logger/options.rb
- test/controllers/articles_controller_test.rb
Fixes #149.
An alternative of #215.
Currently, a message of action log is a fixed value. Some services(e.g. Datadog) emphasize a `message` value. So sometimes we want to add more information to that column.
This PR adds the config to customize that value. We can change the value like the following.
```ruby
config.rails_semantic_logger.action_message_format = -> (message, payload) do
"#{message} - #{payload[:controller]}##{payload[:action]}"
end
```
> Allow to customize a message of action log

- lib/rails_semantic_logger/active_record/log_subscriber.rb
https://github.com/reidmorrison/rails_semantic_logger/issues/249
Don't check only for Rails 7, check for all version after also (Rails 8 and the future ones).
I see that on other parts of code you have conditions where you check if Rails version is bigger than 7 so I think this would be good to have for compatibility with new Rails versions. Of course, if there would be some needed changes in some Rails version in future, we would add new condition, but in case there is no need for that like now on Rails 8, we wouldn't have errors.
> Fix checking of Rails version on ActiveRecord log subscriber

- lib/rails_semantic_logger/sidekiq/defaults.rb
This pull request updates the `RailsSemanticLogger` integration with Sidekiq by ensuring the logger references are fully qualified to avoid potential namespace conflicts.
Namespace qualification updates:
* [`lib/rails_semantic_logger/sidekiq/defaults.rb`](diffhunk://#diff-dbf2af746a7d1efaf7a1aa9f7a17ce46bc83f632da75276422d7cfba4809cb0fL12-R12): Updated `Sidekiq.logger` to `::Sidekiq.logger` in two places within the `Defaults` module to ensure proper namespace resolution. [[1]](diffhunk://#diff-dbf2af746a7d1efaf7a1aa9f7a17ce46bc83f632da75276422d7cfba4809cb0fL12-R12) [[2]](diffhunk://#diff-dbf2af746a7d1efaf7a1aa9f7a17ce46bc83f632da75276422d7cfba4809cb0fL21-R21)
> Fix sidekiq logger reference in ERROR_HANDLER

- lib/rails_semantic_logger.rb
In the app I'm working on, we've (mostly) silenced logs in CI via
```rb
if ENV['CI']
config.log_level = :fatal
end
```
There are some tests that explicitly test logging, though, so for the duration of those test we drop the log level down back down to `:info`.
While upgrading this app from Rails 7 to Rails 7.1, we saw some odd failures in these tests — both the Rails-default logs and the `rails_semantic_logger` logs were being printed. It seems to be due to the changes made in https://github.com/rails/rails/pull/45796 to the `listeners_for` method, which `rails_semantic_logger` uses to unsubscribe existing log subscribers. In short:
- With `log_level = :fatal`, when `rails_semantic_logger` is first loaded, `listeners_for` doesn't return the Rails-default log subscribers, since they're …
> Unsubscribe all listeners in Rails >= 7.1

- lib/rails_semantic_logger/engine.rb
https://github.com/reidmorrison/rails_semantic_logger/issues/237
Adds SolidQueue as an auto-detected framework. 
Reading through the Solid Queue docs it says:
> Solid Queue's supervisor will fork a separate process for each supervised worker/dispatcher/scheduler.
~ https://github.com/rails/solid_queue?tab=readme-ov-file#workers-dispatchers-and-scheduler
It also offers four hooks
```ruby
SolidQueue.on_start
SolidQueue.on_stop
SolidQueue.on_worker_start
SolidQueue.on_worker_stop
```
~ https://github.com/rails/solid_queue?tab=readme-ov-file#lifecycle-hooks
So I found that by adding
```rb
SolidQueue.on_worker_start do
SemanticLogger.reopen
end
```
The logs started to appear in STDOUT. 
----
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Auto-detect SolidQueue

- lib/rails_semantic_logger/engine.rb
Rails apps can run in API only mode, which means they do not have an asset pipeline. If one tries to call config.assets for an app like that one gets the following crash:
```
NoMethodError: undefined method 'assets' for an instance of Rails::Application::Configuration (NoMethodError)
Did you mean?  asset_host
my-app/config/environment.rb:7:in '<main>'
/bundle:25:in 'Kernel#load'
bundle:25:in '<main>'
```
The code a few lines above (95-100) ([ref](https://github.com/0robustus1/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L95-L100)) is already written defensively. This does the same for this invocation of config.assets.
> avoid crashing in no assets (api only) mode
